"""update admin db

Revision ID: 1054dba056e2
Revises: 54c8f9e89717
Create Date: 2025-03-09 12:52:57.270448

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1054dba056e2"
down_revision = "54c8f9e89717"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.drop_column("admin_email")
        batch_op.drop_column("admin_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("admin_name", mysql.VARCHAR(length=125), nullable=True)
        )
        batch_op.add_column(
            sa.Column("admin_email", mysql.VARCHAR(length=125), nullable=True)
        )

    # ### end Alembic commands ###
