"""add email and name

Revision ID: 54c8f9e89717
Revises:
Create Date: 2025-03-09 12:50:14.629015

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54c8f9e89717"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("admin_name", sa.String(length=125), nullable=True)
        )
        batch_op.add_column(
            sa.Column("admin_email", sa.String(length=125), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.drop_column("admin_email")
        batch_op.drop_column("admin_name")

    # ### end Alembic commands ###
